### ISSUE TITLE
Request: Make sortPriority independent of showMultiSort

### ISSUE THREAD

**Issue by boredstiff** [dimbslmh/bootstrap-table-multiple-sort#2]
Forgive this if I'm missing something important, but I believe it would be better if showMultiSort was independent of sortPriority. As of now, if I use sortPriority and give it an order, showMultiSort appears to need to be true for the priority to work. If I say false or don't define showMultiSort in the table, the sortPriority has no effect.

Therefore, for my table, I'm having to override the multisort icon visibility in the Sass/CSS.

**Comment by dimbslmh** [comment]
PR was merged: https://github.com/wenzhixin/bootstrap-table/pull/2984

I apologize for the very late response.
